version: '3.8'

services:
  launcher:
    build:
      context: .
      network: host
    environment:
      - PORT=5000
      - HTTP_PORT=31337
      - ETH_RPC_URL=https://eth.llamarpc.com
      - PUBLIC_IP=127.0.0.1
      - SHARED_SECRET=super_super_secret_1337
    ports:
      - "5000:5000"
      - "31337:31337"